# .github/workflows/docker-build.yml
name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with 'v' pushed via git
  create: # Trigger when a ref (branch or tag) is created via UI or API

jobs:
  build-and-push:
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) || (github.event_name == 'create' && github.ref_type == 'tag' && startsWith(github.ref, 'v'))
    name: Build and Push Multi-Platform Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add a step to reliably get the tag name for both events
      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: |
          TAG_NAME=""
          # For push or create tag events, github.ref is 'refs/tags/tagname'
          # For create tag event, github.ref is just 'tagname'
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
          elif [[ "${{ github.event_name }}" == "create" && "${{ github.ref_type }}" == "tag" ]]; then
             TAG_NAME=${GITHUB_REF}
          fi

          # Ensure it matches the desired 'v*' pattern
          if [[ "$TAG_NAME" =~ ^v.+ ]]; then
             echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT
             echo "Using tag: ${TAG_NAME}"
          else
             echo "Ref '${TAG_NAME}' is not a valid 'v*' tag. Skipping build."
             # Optional: Exit cleanly to stop subsequent steps if needed
             # exit 78 # Neutral exit code
             echo "tag=" >> $GITHUB_OUTPUT # Ensure output is empty if invalid
          fi

      - name: Set up QEMU
        if: steps.extract_tag.outputs.tag != '' # Run only if tag is valid
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.extract_tag.outputs.tag != '' # Run only if tag is valid
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: steps.extract_tag.outputs.tag != '' # Run only if tag is valid
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.extract_tag.outputs.tag != '' # Run only if tag is valid
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dinamic/golang-templ:${{ steps.extract_tag.outputs.tag }}
            dinamic/golang-templ:latest
          # cache-from: type=gha # Optional cache
          # cache-to: type=gha,mode=max # Optional cache

      - name: Print pushed tags
        if: steps.extract_tag.outputs.tag != '' # Run only if tag is valid
        run: |
          echo "Pushed Docker tags: dinamic/golang-templ:${{ steps.extract_tag.outputs.tag }}, dinamic/golang-templ:latest"